/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * splashScreen.java
 *
 * Created on Dec 7, 2009, 4:17:00 PM
 */

package speedygram;

import java.awt.*;
import java.awt.Font.*;
import java.io.*;
import java.io.File.*;
import java.io.IOException.*;
/**
 *
 * @author lnewby
 */
public class splashScreen extends javax.swing.JFrame {

    /** Creates new form splashScreen */
    public splashScreen() {

        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/speedygram/fonts/dakota__.ttf").openStream()));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/speedygram/fonts/gillsansultrabold.ttf").openStream()));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/speedygram/fonts/gillsans.ttf").openStream()));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/speedygram/fonts/gillsansbold.ttf").openStream()));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("/speedygram/fonts/lucidagrande.ttf").openStream()));

        } catch (IOException e) {
        } catch (FontFormatException ffe){
        }

        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SpeedyGramBtn = new javax.swing.JButton();
        playNewGameBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(594, 408));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(594, 408));
        jPanel1.setSize(new java.awt.Dimension(594, 408));

        SpeedyGramBtn.setBackground(new java.awt.Color(255, 255, 255));
        SpeedyGramBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speedygram/images/speedy_gram_logo.png"))); // NOI18N
        SpeedyGramBtn.setBorderPainted(false);
        SpeedyGramBtn.setContentAreaFilled(false);
        SpeedyGramBtn.setFocusPainted(false);

        playNewGameBtn.setFont(new java.awt.Font("Gill Sans Bold", 1, 18)); // NOI18N
        playNewGameBtn.setForeground(new java.awt.Color(0, 51, 255));
        playNewGameBtn.setText("Play New Game");
        playNewGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playNewGameBtnActionPerformed(evt);
            }
        });

        quitBtn.setText("Exit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(playNewGameBtn)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(SpeedyGramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(quitBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(SpeedyGramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playNewGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(quitBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playNewGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playNewGameBtnActionPerformed
        // TODO add your handling code here:
        Steps mySteps = new Steps();
        mySteps.setLocationRelativeTo(null);
        mySteps.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_playNewGameBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SpeedyGramBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playNewGameBtn;
    private javax.swing.JButton quitBtn;
    // End of variables declaration//GEN-END:variables

}
